/*
Filterscript generated using Zamaroht's TextDraw Editor Version 1.0 (v3.1 Current).
Designed for SA-MP 0.3a.

Time and Date: 2013-12-22 @ 16:33:17

Instructions:
1- Compile this file using the compiler provided with the sa-mp server package.
2- Copy the .amx file to the filterscripts directory.
3- Add the filterscripts in the server.cfg file (more info here:
http://wiki.sa-mp.com/wiki/Server.cfg)
4- Run the server!

Disclaimer:
You have full rights over this file. You can distribute it, modify it, and
change it as much as you want, without having to give any special credits.
*/

#include <a_samp>
new playerid;
new Text:Textdraw0;
new Text:Textdraw1;
new Text:Textdraw2;
new Text:Textdraw3;
new Text:Textdraw4;
new Text:Textdraw5;
new Text:Textdraw6;
new Text:Textdraw7;
forward animatedhumu();
public animatedhumu()
{
	TextDrawShowForPlayer(playerid, Textdraw0);
	TextDrawHideForPlayer(playerid, Textdraw7);
	SetTimer("humu2",1000,1);
}
forward humu2();
public humu2()
{
	TextDrawShowForPlayer(playerid, Textdraw1);
	TextDrawHideForPlayer(playerid, Textdraw0);
	SetTimer("humu3",1000,1);
}
forward humu3();
public humu3()
{
	TextDrawShowForPlayer(playerid, Textdraw2);
	TextDrawHideForPlayer(playerid, Textdraw1);
	SetTimer("humu4",1000,1);
}
forward humu4();
public humu4()
{
	TextDrawShowForPlayer(playerid, Textdraw3);
	TextDrawHideForPlayer(playerid, Textdraw2);
	SetTimer("humu5",1000,1);
}
forward humu5();
public humu5()
{
	TextDrawShowForPlayer(playerid, Textdraw4);
	TextDrawHideForPlayer(playerid, Textdraw3);
	SetTimer("humu6",1000,1);
}
forward humu6();
public humu6()
{
	TextDrawShowForPlayer(playerid, Textdraw5);
	TextDrawHideForPlayer(playerid, Textdraw4);
	SetTimer("humu7",1000,1);
}
forward humu7();
public humu7()
{
	TextDrawShowForPlayer(playerid, Textdraw6);
	TextDrawHideForPlayer(playerid, Textdraw5);
	SetTimer("humu8",1000,1);
}
forward humu8();
public humu8()
{
	TextDrawShowForPlayer(playerid, Textdraw7);
	TextDrawHideForPlayer(playerid, Textdraw6);
	SetTimer("animatedhumu",1000,1);
}
public OnFilterScriptInit()
{
	print("Textdraw file generated by");

	SetTimer("animatedhumu",1000,1);
	// Create the textdraws:
	Textdraw0 = TextDrawCreate(170.000000, 370.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw0, 255);
	TextDrawFont(Textdraw0, 3);
	TextDrawLetterSize(Textdraw0, 0.500000, 1.500000);
	TextDrawColor(Textdraw0, -1);
	TextDrawSetOutline(Textdraw0, 1);
	TextDrawSetProportional(Textdraw0, 1);
	TextDrawSetSelectable(Textdraw0, 0);

	Textdraw1 = TextDrawCreate(170.000000, 373.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw1, 255);
	TextDrawFont(Textdraw1, 3);
	TextDrawLetterSize(Textdraw1, 0.500000, 1.500000);
	TextDrawColor(Textdraw1, -1);
	TextDrawSetOutline(Textdraw1, 1);
	TextDrawSetProportional(Textdraw1, 1);
	TextDrawSetSelectable(Textdraw1, 0);

	Textdraw2 = TextDrawCreate(170.000000, 376.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw2, 255);
	TextDrawFont(Textdraw2, 3);
	TextDrawLetterSize(Textdraw2, 0.500000, 1.500000);
	TextDrawColor(Textdraw2, -1);
	TextDrawSetOutline(Textdraw2, 1);
	TextDrawSetProportional(Textdraw2, 1);
	TextDrawSetSelectable(Textdraw2, 0);

	Textdraw3 = TextDrawCreate(170.000000, 379.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw3, 255);
	TextDrawFont(Textdraw3, 3);
	TextDrawLetterSize(Textdraw3, 0.500000, 1.500000);
	TextDrawColor(Textdraw3, -1);
	TextDrawSetOutline(Textdraw3, 1);
	TextDrawSetProportional(Textdraw3, 1);
	TextDrawSetSelectable(Textdraw3, 0);

	Textdraw4 = TextDrawCreate(170.000000, 382.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw4, 255);
	TextDrawFont(Textdraw4, 3);
	TextDrawLetterSize(Textdraw4, 0.500000, 1.500000);
	TextDrawColor(Textdraw4, -1);
	TextDrawSetOutline(Textdraw4, 1);
	TextDrawSetProportional(Textdraw4, 1);
	TextDrawSetSelectable(Textdraw4, 0);

	Textdraw5 = TextDrawCreate(170.000000, 385.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw5, 255);
	TextDrawFont(Textdraw5, 3);
	TextDrawLetterSize(Textdraw5, 0.500000, 1.500000);
	TextDrawColor(Textdraw5, -1);
	TextDrawSetOutline(Textdraw5, 1);
	TextDrawSetProportional(Textdraw5, 1);
	TextDrawSetSelectable(Textdraw5, 0);

	Textdraw6 = TextDrawCreate(170.000000, 388.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw6, 255);
	TextDrawFont(Textdraw6, 3);
	TextDrawLetterSize(Textdraw6, 0.500000, 1.500000);
	TextDrawColor(Textdraw6, -1);
	TextDrawSetOutline(Textdraw6, 1);
	TextDrawSetProportional(Textdraw6, 1);
	TextDrawSetSelectable(Textdraw6, 0);

	Textdraw7 = TextDrawCreate(170.000000, 391.000000, "This Is Text");
	TextDrawBackgroundColor(Textdraw7, 255);
	TextDrawFont(Textdraw7, 3);
	TextDrawLetterSize(Textdraw7, 0.500000, 1.500000);
	TextDrawColor(Textdraw7, -1);
	TextDrawSetOutline(Textdraw7, 1);
	TextDrawSetProportional(Textdraw7, 1);
	TextDrawSetSelectable(Textdraw7, 0);
	
	for(new i; i < MAX_PLAYERS; i ++)
	{
		if(IsPlayerConnected(i))
		{
			TextDrawShowForPlayer(i, Textdraw0);
		}
	}
	return 1;
}
public OnPlayerSpawn(playerid)
{
	TextDrawShowForPlayer(playerid, Textdraw0);
	return 1;
}
